export enum Catalog {
    HOME = "home",
    ELECTRONICS = "electronics",
    CLOTHING = "clothing",
    BOOKS = "books",
    BEAUTY = "beauty",
    SPORTS = "sports",
    FURNITURE = "furniture",
    TOYS = "toys",
    FOOD = "food",
    AUTOMOTIVE = "automotive",
    JEWELRY = "jewelry",
    MUSIC = "music",
    PET_SUPPLIES = "pet supplies",
    HEALTH = "health",
    ART = "art",
    STATIONERY = "stationery",
    OUTDOORS = "outdoors",
    VIDEO_GAMES = "video games",
    SOFTWARE = "software",
    OTHER = "other",
}